### ISSUE TITLE
Is it possible to run the model to recognize other languages?

### ISSUE THREAD

**Issue by sanek11591** [huggingface/distil-whisper#15] opened 2023-11-03 11:27 UTC
Can this model be used for other languages ​​and if so, how?

**Comment by sanchit-gandhi** [comment] 2023-11-03 14:22
Currently English-only with a multilingual release planned, _c.f._ https://github.com/huggingface/distil-whisper/issues/6#issuecomment-1790869897

**Comment by sanchit-gandhi** [comment] 2023-11-06 10:18
Closing as this is a duplicate of https://github.com/huggingface/distil-whisper/issues/6#issuecomment-1790869897!

**Closed by sanchit-gandhi** 2023-11-06 10:18 UTC
